### ISSUE TITLE
[Firefox] Download links is 404?

### ISSUE THREAD

**Issue by azu** [RReverser/github-editorconfig#5]
https://addons.mozilla.org/en-US/firefox/addon/github-editorconfig/ is not found?

**Comment by RReverser** [comment]
Nope, that's why download link in README points to download from GitHub itself: https://github.com/RReverser/github-editorconfig/releases/download/1.1.0/githubeditorconfig_1.1.0.xpi

Where did you find that link?

**Comment by azu** [comment]
@RReverser Thanks!

> Where did you find that link?

Here : http://rreverser.com/gh-github-editorconfig/

**Comment by RReverser** [comment]
Oh, right, didn't update blog post. Thanks, will do now!
